version: "3.8"
services:
  demo:
    build: .
    container_name: portfolio-foundation-demo
    ports:
      - "7860:7860"
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
      - OPENAI_API_KEY=PLACEHOLDER
    command: ["python", "app/demo_gradio.py"]
